### ISSUE TITLE
it's not working 

### ISSUE THREAD

**Issue by vcbat** [SilentDemonSD/WZML-X#278]
while deploying error module not found "pytz" any solution

**Comment by REALXLOLX** [comment]
> while deploying error module not found "pytz" any solution

pip install pytz

**Comment by vcbat** [comment]
not working brh

**Comment by REALXLOLX** [comment]
> not working brh

Send screenshot or full logs

**Comment by JohnCale47** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 3, in <module>
    from pytz import timezone
ModuleNotFoundError: No module named 'pytz'
root@instance-20220531-2245:/home/ubuntu/mirror/WZML-X# pip install pytz
Collecting pytz
  Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 2.1 MB/s
Installing collected packages: pytz
Successfully installed pytz-2024.2
root@instance-20220531-2245:/home/ubuntu/mirror/WZML-X# sudo docker run -p 80:80 -p 8080:8080 wzmlx
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 3, in <module>
    from pytz import timezone
ModuleNotFoundError: No module named 'pytz'

```

**Comment by REALXLOLX** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/usr/src/app/bot/__init__.py", line 3, in <module>
>     from pytz import timezone
> ModuleNotFoundError: No module named 'pytz'
> root@instance-20220531-2245:/home/ubuntu/mirror/WZML-X# pip install pytz
> Collecting pytz
>   Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
>      |████████████████████████████████| 508 kB 2.1 MB/s
> Installing collected packages: pytz
> Successfully installed pytz-2024.2
> root@instance-20220531-2245:/home/ubuntu/mirror/WZML-X# sudo docker run -p 80:80 -p 8080:8080 wzmlx
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/usr/src/app/bot/__init__.py", line 3, in <module>
>     from pytz import timezone
> ModuleNotFoundError: No module named 'pytz'
> ```

Use python virtual environments if you don't know Contact me in 
@Losting007telegram
